/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'BldcBcHall' 
 * Target:  'TLE9879 EvalKit' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "tle987x.h"

/* Infineon::Device:SDK:ADC1@0.3.0 */
#define RTE_DEVICE_SDK_ADC1
/* Infineon::Device:SDK:BDRV@0.6.1 */
#define RTE_DEVICE_SDK_BDRV
/* Infineon::Device:SDK:BOOTROM@0.3.3 */
#define RTE_DEVICE_SDK_BROM
/* Infineon::Device:SDK:CCU6@0.4.1 */
#define RTE_DEVICE_SDK_CCU6
/* Infineon::Device:SDK:GPT12E@0.2.2 */
#define RTE_DEVICE_SDK_GPT12E
/* Infineon::Device:SDK:INT@0.2.3 */
#define RTE_DEVICE_SDK_INT
/* Infineon::Device:SDK:ISR@0.2.9 */
#define RTE_DEVICE_SDK_ISR
/* Infineon::Device:SDK:PORT@0.6.0 */
#define RTE_DEVICE_SDK_PORT
/* Infineon::Device:SDK:SCU@0.5.7 */
#define RTE_DEVICE_SDK_SCU
/* Infineon::Device:SDK:SSC@0.1.8 */
#define RTE_DEVICE_SDK_SSC
/* Infineon::Device:SDK:WDT1@0.3.3 */
#define RTE_DEVICE_SDK_WDT1


#endif /* RTE_COMPONENTS_H */
