/**:
  ros__parameters:
    video_device: "/dev/video0"
    framerate: 10.0
    io_method: "mmap"
    frame_id: "cam1"
    pixel_format: "yuyv2rgb"
    color_format: "yuyv2rgb"
    image_width: 320
    image_height: 240
    camera_name: "cam1"
